export const mockData = {
    sites: ["All Sites", "Main Campus", "North Clinic", "Eastside Office", "Hospital - Metro"],
    cashPosition: { total: 1284750, ar: 892400, ap: 234100, runway: 87, trend: [820, 910, 875, 960, 1050, 1120, 1200, 1284] },
    revenueByPayor: [
        { name: "Medicare", value: 42, amount: 187400, color: "#3B82F6" },
        { name: "Medicaid", value: 18, amount: 80200, color: "#06B6D4" },
        { name: "BlueCross", value: 22, amount: 97900, color: "#8B5CF6" },
        { name: "Aetna", value: 11, amount: 48900, color: "#10B981" },
        { name: "Other", value: 7, amount: 31100, color: "#F59E0B" },
    ],
    revenueByProvider: [
        { name: "Dr. Rafiq", revenue: 124500, expenses: 68000, rvu: 1840 },
        { name: "Dr. Chen", revenue: 98700, expenses: 54200, rvu: 1520 },
        { name: "Dr. Patel", revenue: 87300, expenses: 49100, rvu: 1340 },
        { name: "Dr. Williams", revenue: 115200, expenses: 63000, rvu: 1720 },
    ],
    revenueBySite: [
        { site: "Main Campus", revenue: 248000, expenses: 142000 },
        { site: "North Clinic", revenue: 187000, expenses: 108000 },
        { site: "Eastside Office", revenue: 143000, expenses: 89000 },
        { site: "Hospital - Metro", revenue: 98000, expenses: 58000 },
    ],
    arAging: [
        { bucket: "0–30 days", amount: 312000, pct: 35, color: "#10B981" },
        { bucket: "31–60 days", amount: 267000, pct: 30, color: "#3B82F6" },
        { bucket: "61–90 days", amount: 178000, pct: 20, color: "#F59E0B" },
        { bucket: "91–120 days", amount: 89000, pct: 10, color: "#EF4444" },
        { bucket: "120+ days", amount: 45000, pct: 5, color: "#991B1B" },
    ],
    expenses: {
        payroll: 432000, nonPayroll: 218000,
        categories: [
            { name: "Salaries", amount: 380000 }, { name: "Benefits", amount: 52000 },
            { name: "Rent", amount: 84000 }, { name: "Supplies", amount: 67000 },
            { name: "Tech", amount: 38000 }, { name: "Insurance", amount: 29000 },
        ],
    },
    staff: [
        { id: 1, name: "Dr. Shahid Rafiq", role: "Lead Neurologist", site: "Main Campus", type: "Provider", status: "Active", license: "2026-08-15" },
        { id: 2, name: "Dr. Linda Chen", role: "Neurologist", site: "North Clinic", type: "Provider", status: "Active", license: "2025-12-01" },
        { id: 3, name: "Dr. Arjun Patel", role: "Neurologist", site: "Eastside Office", type: "Provider", status: "Active", license: "2026-03-22" },
        { id: 4, name: "Dr. Sarah Williams", role: "Neurologist", site: "Hospital - Metro", type: "Provider", status: "Active", license: "2027-01-10" },
        { id: 5, name: "Maria Gonzalez", role: "Practice Administrator", site: "Main Campus", type: "Admin", status: "Active", license: "N/A" },
        { id: 6, name: "James Park", role: "Billing Manager", site: "Main Campus", type: "Admin", status: "Active", license: "N/A" },
        { id: 7, name: "Priya Singh", role: "Medical Assistant", site: "North Clinic", type: "Clinical", status: "Active", license: "2026-06-30" },
        { id: 8, name: "Tom Bradley", role: "NP", site: "Eastside Office", type: "Provider", status: "Credentialing", license: "2026-11-15" },
    ],
    credentialing: [
        { provider: "Dr. Arjun Patel", item: "DEA Registration", expiry: "2026-03-22", status: "warning", daysLeft: 23 },
        { provider: "Dr. Linda Chen", item: "Board Certification", expiry: "2025-12-01", status: "critical", daysLeft: -87 },
        { provider: "Tom Bradley", item: "Hospital Privileges", expiry: null, status: "pending", daysLeft: null },
        { provider: "Dr. Rafiq", item: "State License - NY", expiry: "2026-08-15", status: "ok", daysLeft: 169 },
        { provider: "Dr. Williams", item: "Malpractice Insurance", expiry: "2027-01-10", status: "ok", daysLeft: 318 },
    ],
    contracts: [
        { id: 1, name: "Medicare Participation Agreement", type: "Payor", status: "Active", expiry: "2026-12-31", value: "$0", sites: "All" },
        { id: 2, name: "BlueCross Provider Agreement", type: "Payor", status: "Renewal Window", expiry: "2026-04-15", value: "$0", sites: "All" },
        { id: 3, name: "Dr. Rafiq Employment Contract", type: "Employment", status: "Active", expiry: "2027-06-30", value: "$420K/yr", sites: "Main Campus" },
        { id: 4, name: "Dr. Chen Employment Contract", type: "Employment", status: "Active", expiry: "2026-09-01", value: "$380K/yr", sites: "North Clinic" },
        { id: 5, name: "Metro Hospital Service Agreement", type: "Institutional", status: "Active", expiry: "2026-06-30", value: "$180K/yr", sites: "Hospital" },
        { id: 6, name: "Office Lease - Main Campus", type: "Vendor", status: "Active", expiry: "2028-01-01", value: "$84K/yr", sites: "Main Campus" },
        { id: 7, name: "eClinicalWorks EHR License", type: "Vendor", status: "Active", expiry: "2026-08-31", value: "$38K/yr", sites: "All" },
        { id: 8, name: "Aetna Network Agreement", type: "Payor", status: "Draft", expiry: "N/A", value: "N/A", sites: "All" },
    ],
    alerts: [
        { id: 1, type: "critical", module: "HR", title: "License Expired", desc: "Dr. Chen board certification expired 87 days ago", time: "2h ago" },
        { id: 2, type: "warning", module: "Contracts", title: "Renewal Due", desc: "BlueCross agreement expires in 47 days", time: "4h ago" },
        { id: 3, type: "warning", module: "HR", title: "DEA Renewal", desc: "Dr. Patel DEA registration expires in 23 days", time: "1d ago" },
        { id: 4, type: "info", module: "Financial", title: "Data Updated", desc: "March billing report imported successfully", time: "2d ago" },
        { id: 5, type: "info", module: "Contracts", title: "New Contract", desc: "Aetna agreement draft uploaded", time: "3d ago" },
    ],
    practiceScore: 74,
    monthlyRevenue: [
        { month: "Aug", revenue: 391000, expenses: 268000 }, { month: "Sep", revenue: 418000, expenses: 281000 },
        { month: "Oct", revenue: 445000, expenses: 294000 }, { month: "Nov", revenue: 402000, expenses: 278000 },
        { month: "Dec", revenue: 389000, expenses: 271000 }, { month: "Jan", revenue: 467000, expenses: 302000 },
        { month: "Feb", revenue: 445500, expenses: 295000 },
    ],
};
